"""Added many-to-many realtions (table VPS - Module) 2

Revision ID: 76004321a311
Revises: b52bff52ec42
Create Date: 2025-02-13 14:00:57.453035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76004321a311'
down_revision: Union[str, None] = 'b52bff52ec42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
