"""History table added, VPS table updated with relationship

Revision ID: a98abfe29bc5
Revises: ebe1b0f0ae7c
Create Date: 2025-02-13 13:01:06.474008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98abfe29bc5'
down_revision: Union[str, None] = 'ebe1b0f0ae7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
