"""Added many-to-many realtions (table VPS - Module)

Revision ID: b52bff52ec42
Revises: 53a517ad4ead
Create Date: 2025-02-13 13:57:55.689280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52bff52ec42'
down_revision: Union[str, None] = '53a517ad4ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
